[auth]
site_url = "https://staked.bootstrapquant.com"
additional_redirect_urls = ["https://staked.bootstrapquant.com/**", "http://localhost:3000/**"]

[auth.email]
enable_signup = true

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
